Granite 3.1
ibm-granite-community/granite-kitchen pull request #40
Opened 2024-12-13 17:18 UTC by gabe-l-hart

## PR Checklist

### Model Interaction

- [ ] **Flexible LLM platform support** The platform should be easily switchable. Use LangChain or LlamaIndex.
- [ ] **Use prompt guide corresponding to the model**  For example for [Granite 3.x Language Models](https://www.ibm.com/granite/docs/models/granite/#prompt-anatomy)

### Data

- [ ] **Example data**: Follow the example data guidance.

### Notebook requirements

- [x] **Notebook outputs cleared**: Ensure all notebook outputs are cleared.
- [ ] **Automated testing**: Add the recipe to the automated tests as described [here](https://github.com/ibm-granite-community/community/wiki/Automated-Validation)
- [ ] **Test in Google Colab**:
    - [ ] Test that it works in Google Colab (Python 3.10.12).
    - [ ] Colab has its own package set and Python version, so ensure compatibility.
- [ ] **Test locally**:
    - [ ] Ensure the code works in a fresh Python virtual environment (venv).
- [ ] **Standard access to secrets and variables** Include `!pip install git+https://github.com/ibm-granite-community/utils` in the first code cell in order to make `get_env_var` available to accessing secrets and variables in the recipe.

### Incoming References

- [ ] **README.md updates**:
    - [ ] Add a link to the recipe in the Table of Contents (ToC).
    - [ ] Include a Colab button after that link.

### GitHub

- [x] **Commits signed**: All commits must be GPG or SSH signed.
- [x] **DCO Compliance**: Developer Certificate of Origin (DCO) applies to the code, documentation, and any example data provided. Ensure commits are signed off.

2024-12-17 20:06 UTC, bjhargrave requested changes

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Components/Langchain_Embeddings_Models.ipynb
> +    "embeddings_model = HuggingFaceEmbeddings(model_name=\"ibm-granite/granite-embedding-278m-multilingual\")"
Should this be 30m-english as it is similar in size/language to the embedding it is replacing?

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Components/Langchain_LLMs.ipynb
> +    "    model_id=\"ibm/granite-3.1-8b-instruct\",\n",
```suggestion
    "    model_id=\"ibm/granite-3-8b-instruct\",\n",
```

They did not change the id.

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb
> +    "[`ibm/granite-3.1-8b-instruct`](https://dataplatform.cloud.ibm.com/wx/samples/models/ibm/granite-3.1-8b-instruct?context=wx)\n",
```suggestion
    "[`ibm/granite-3-8b-instruct`](https://dataplatform.cloud.ibm.com/wx/samples/models/ibm/granite-3-8b-instruct?context=wx)\n",
```

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb
> +    "[`ibm/granite-3.1-2b-instruct`](https://dataplatform.cloud.ibm.com/wx/samples/models/ibm/granite-3.1-2b-instruct?context=wx)\n",
```suggestion
    "[`ibm/granite-3-2b-instruct`](https://dataplatform.cloud.ibm.com/wx/samples/models/ibm/granite-3-2b-instruct?context=wx)\n",
```

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb
> +    "[`ibm/granite-3.1-1b-a400m-instruct`](https://dataplatform.cloud.ibm.com/wx/samples/models/ibm/granite-3.1-1b-a400m-instruct?context=wx)"
These won't be on Watsonx until sometime in the future.

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb
> +    "# model_id = \"ibm/granite-3.1-2b-instruct\"\n",
```suggestion
    "model_id = \"ibm/granite-3-8b-instruct\"\n",
    "# model_id = \"ibm/granite-3-2b-instruct\"\n",
```

2024-12-17 20:06 UTC, bjhargrave commented on recipes/Getting_Started/Getting_Started_with_WatsonX.ipynb
> +    "# model_id = \"ibm/granite-3.1-1b-a400m-instruct\""
These won't be on watsonx till later.

2024-12-18 15:29 UTC, gabe-l-hart commented
Thanks @bjhargrave! All comments resolved

2024-12-18 15:32 UTC, bjhargrave approved these changes

2024-12-18 17:43 UTC, merged